# .github/workflows/devsecops.yml 
name: DevGuard DevSecOps

on:
    push:

permissions:
    contents: read
    packages: write

jobs:
    find-leaked-secrets:
        uses: l3montree-dev/devguard-ci-components/.github/workflows/secret-scanning.yml@main
        with:
            devguard-asset-name: "l3montree-cybersecurity/projects/l3montree-intern/assets/pomodoro"
            devguard-api-url: "https://api.main.devguard.org"
            devguard-web-ui: "https://main.devguard.org"
        secrets:
            devguard-token: "${{ secrets.DEVGUARD_TOKEN }}" 

    bad-practice-finder:
        uses: l3montree-dev/devguard-ci-components/.github/workflows/static-application-security-testing.yml@main
        with:
            devguard-asset-name: "l3montree-cybersecurity/projects/l3montree-intern/assets/pomodoro"
            devguard-api-url: "https://api.main.devguard.org"
            devguard-web-ui: "https://main.devguard.org"
        secrets:
            devguard-token: "${{ secrets.DEVGUARD_TOKEN }}" 
    infrastructure-as-code-scanning:
        uses: l3montree-dev/devguard-ci-components/.github/workflows/iac.yml@main
        with:
            devguard-asset-name: "l3montree-cybersecurity/projects/l3montree-intern/assets/pomodoro"
            devguard-api-url: "https://api.main.devguard.org"
            devguard-web-ui: "https://main.devguard.org"
        secrets:
            devguard-token: "${{ secrets.DEVGUARD_TOKEN }}" 

    dependency-scanning:
        uses: l3montree-dev/devguard-ci-components/.github/workflows/software-composition-analysis.yml@main
        with:
            devguard-asset-name: "l3montree-cybersecurity/projects/l3montree-intern/assets/pomodoro"
            devguard-api-url: "https://api.main.devguard.org"
            devguard-web-ui: "https://main.devguard.org"
        secrets:
            devguard-token: "${{ secrets.DEVGUARD_TOKEN }}" 